### ISSUE TITLE
Migrate server to typescript

### ISSUE THREAD

**Issue by bradtaniguchi** [CaraLagumen/baristabook#1]
I noticed the code within the `server` folder, which is used to run the backend is written in JS. The back-end could be written in TS using the same tooling as the client app.

This will require changes to how the backend is ran, and deployed to integrate typescript.

**Comment by CaraLagumen** [comment]
Will do! 👍

**Comment by CaraLagumen** [comment]
Finished migrating entire server! :D Thank you!

https://github.com/CaraLagumen/baristabook/commit/ed0dd164e450f637e392d07e9943f764acc54582
