### ISSUE TITLE
Update README with notes on how to run the app

### ISSUE THREAD

**Issue by bradtaniguchi** [CaraLagumen/baristabook#2]
The current README is the default one provided by the angular-cli. Having details on being able to setup and run the project locally would be helpful to those that what to also run the project. 
I have a vague idea where I ran the following:

1. Install deps with `npm install`
2. Run the front-end using `npm run start`, this starts angular
3. Run the backend by first installing `nodemon` (I had to install this manually, might be missing from package.json), then running `npm run dev`. I currently get the following error:

```
[nodemon] 2.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
undefined
Uncaught exception. Shutting down...
TypeError Cannot read property 'replace' of undefined
[nodemon] app crashed - waiting for file changes before starting...
```

My guess is I'm forgetting another step somewhere, so the fact the error is super vague shouldn't matter too much. :)

**Comment by CaraLagumen** [comment]
AHH! Sorry about the nodemon! I will put it on my dev dependencies! My config.env is also missing. I'm currently not sure if I want to expose this to the general public but I have messaged you privately for one you could use! As for the README, not a problem! I will work on this possibly when the app is done and made a version more available to others. I hope this is okay. Thanks!

**Comment by bradtaniguchi** [comment]
Yes keep the environment variables **out of source control (git)**, your right in that you don't want to expose that stuff to the public. Do update the README tho with documentation on what you need to run the project locally, so those that want to run it can. The more pain free the project is to run, the easier it will be for anyone wanting to help. 😄

**Comment by CaraLagumen** [comment]
I've updated the README. Thank you Brad.

https://github.com/CaraLagumen/baristabook/commit/75d817060f78857320d05187d042e405a3c1472e
