### ISSUE TITLE
Update manual unsubscribes

### ISSUE THREAD

**Issue by bradtaniguchi** [CaraLagumen/baristabook#3]
Currently the code manually unsubscribes, like here: https://github.com/CaraLagumen/baristabook/blob/d5bccbdbe82be654d1e72b055f4e767ca2abdb99/src/app/auth/login/login.component.ts#L35
 
Most of these situations can be changed to leverage common approaches that usually result in easier to maintain code.
Most of the best approaches are mentioned in this article, written by one of the core rxjs team members:
https://medium.com/@benlesh/rxjs-dont-unsubscribe-6753ed4fda87

Alternatively you can leverage the `async` pipe to act as a "subscribe"  in the template itself, which automatically unsubscribes when the component+template is destroyed. This is my personal approach most of the time.
https://alligator.io/angular/async-pipe/

**Comment by CaraLagumen** [comment]
I will keep these bookmarked and noted! This looks like more advanced stuff and I think I better tackle this once I finish diving deeper into rxjs! Very helpful of you once again! Thanks Brad!

Edit: Forgot to mention, the async pipe is something I can try to apply more immediately. I did use it a couple of times in my project. Hehe.

**Comment by bradtaniguchi** [comment]
One of the most commonly abused approaches in Angular is "pipeing to the template", where you setup an rxjs pipe to get what you want, and pass it all the way to the `async` pipe in the template. This requires a working good knowledge of rxjs, and is **heavily** used when using a state management lib like [ngrx](https://ngrx.io/). 

Its fine to use without using a state management lib, but just be careful with situations like subscribing to an http call. As every time you subscribe, you will end up making the http service make an http call, so depending on the use-case, you could end up calling the back-end **a lot**. Just something to keep in mind when using the `async` pipe!

**Comment by CaraLagumen** [comment]
Everything but authentication and router related services are manual subscriptions. Thanks!
