### ISSUE TITLE
Drink search doesn't seem to work if the user hits enter

### ISSUE THREAD

**Issue by bradtaniguchi** [CaraLagumen/baristabook#6]
When entering values into the search bar, and hitting enter, the page refreshes, and upon the refresh the page ends up looking the same as before, without showing any relevant results.

**edit** I looked at the implementation, it looks like as long as you don't hit enter results appear. I think removing the parent form, and leaving the input by itself should help fix the issue, as then hitting enter wont submit the form, and thus it wont "do anything" like refresh the page.

**Comment by CaraLagumen** [comment]
Fixed the issue! Thanks again!

https://github.com/CaraLagumen/baristabook/commit/75d817060f78857320d05187d042e405a3c1472e
